### ISSUE TITLE
macosx install 

### ISSUE THREAD

**Issue by weepy** [ignacio/LuaNode-Socket.IO#1]
tricky ! 

first it's 

luarocks install LuaBitOp (not bitop)

the real hassle is libuuid

=> 
I downloaded e2fsprogs from:

http://prdownloads.sourceforge.net/e2fsprogs/e2fsprogs-1.41.12.tar.gz
cd e2fsprogs-1.41.12
./configure
cd lib/uuid
make
./tst_uuid
cp uuid.so /usr/local/lib/lua/5.1/

**Comment by ignacio** [comment]
Thanks, I've corrected the readme and added the steps you described (and a link to a post I found).

**Comment by weepy** [comment]
yes - that's where i got the information - though it's got a few extra weird
steps there.
